version: '3.9'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace
    networks:
      - default
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    ports:
      - 8081:8081
    networks:
      - default
networks:
  default:
    driver: bridge