version: '3.9'
services:
  dev:
    image: mcr.microsoft.com/devcontainers/universal:2-linux
    command: sleep infinity
    working_dir: /workspace
    volumes:
      - ..:/workspace
    networks:
      - default
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    expose:
      - 8081
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - default
networks:
  default:
    driver: bridge